name: snakemake_ci

on:
 push:
    branches: [ master ]
 pull_request:
    branches_ignore: []

jobs:
 snakemake:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Linting
      uses: snakemake/snakemake-github-action@v1
      with:
        directory: '.'
        snakefile: 'workflow/Snakefile'
        args: '--lint'

    - name: Testing
      uses: snakemake/snakemake-github-action@v1
      with:
          #TODO: Make following a viable directory for testing 
        directory: '.test'
        snakefile: 'workflow/Snakefile'
        args: '--configfile .test/config-simple/config.yaml --use-conda --show-failed-logs --conda-cleanup-pkgs cache --dryrun'
        stagein: ''
        show-disk-usage-on-error: true

